apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/atharvacad/agrocd-phase1.git
    targetRevision: HEAD
    path: nginx-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

